# -*- coding: utf-8 -*-
"""Cau1_Lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sKy95XAc0bhfh9Puu7ZGFrm24P2pIID-
"""

import sympy as sp

x = sp.symbols('x')
f = 4 - x**2
df = sp.diff(f, x)
print("1a - Derivative of f(x) =", df)

import sympy as sp

x = sp.symbols('x')
f = (x - 1)**2 + 1
df = sp.diff(f, x)
print("1b - Derivative of f(x) =", df)

import sympy as sp

t = sp.symbols('t')
g = 1 / (t**2)
dg = sp.diff(g, t)
print("1c - Derivative of g(t) =", dg)

import sympy as sp

z = sp.symbols('z')
k = (1 - z) / 2 * z
dk = sp.diff(k, z)
print("1d - Derivative of k(z) =", dk)

import sympy as sp

z = sp.symbols('z')
k = sp.sqrt(3 * z)
dk = sp.diff(k, z)
print("1e - Derivative of k(z) =", dk)

import sympy as sp

z = sp.symbols('z')
k = sp.sqrt(2 * z + 1)
dk = sp.diff(k, z)
print("1f - Derivative of k(z) =", dk)