# -*- coding: utf-8 -*-
"""cau6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FuhxzEhRW9cRbx9auvSDzfYCnmQkbgVG
"""

f1 = lambda x: x + 5
f2 = lambda x: x**2 - 3

## a)
print("Ham f1(f2(0)) = {}".format(f1(f2(0))) )
## b)
print("Ham f2(f1(0)) = " + str(f2(f1(0))) )
## c)
print("Ham f1(f1(-5)) = {}".format(f1(f1(-5))) )
## d)
print("Ham f2(f2(2)) = " + str(f2(f2(2))) )