# -*- coding: utf-8 -*-
"""Cau5_Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZEFxdRxCCxGYEBqmYrfjlNtcLXLd-Ktq
"""

import math
import sympy as sp

x = sp.symbols('x')
f1_x_c = x**2 - 7
lm_a = sp.limit(f1_x_c, x, 1)

if lm_a == (-6):
  print("Ham so lien tuc tai x = c=1")
else:
  print("Ham so khong lien tuc tai x = c=1")

import math
import sympy as sp

x = sp.symbols('x')
f2_x_c = sp.sqrt(2 * x - 3)
lm_b = sp.limit(f2_x_c, x, 2)

if lm_b == 1:
  print("Ham so lien tuc tai x = c=2")
else:
  print("Ham so khong lien tuc tai x = c=2")