# -*- coding: utf-8 -*-
"""cau_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o8xAMGZ-KA5P3TP7dXNbMBK_2eyhmNJf
"""

import math  #khai báo thư viện 
import numpy as np  #khai báo thư viện 
import sympy as sp  #khai báo thư viện 
import matplotlib.pyplot as plt  #khai báo thư viện 

A = 459
B = 1
fx = lambda x: A * x**2 - 2 * A * x + A #định nghĩa hàm f(x) bằng hàm ẩn danh
gx = lambda x: -A * x**2 + A**2 * x + A #định nghĩa hàm g(x) bằng hàm ẩn danh

def cau_1a():
    print("Câu 1a:")
    print("f(0) = " + str(fx(0))) #giá thị của f(x) khi x bằng 0
    print("f(1) = " + str(fx(1))) #giá thị của f(x) khi x bằng 1
    print("f(A) = " + str(fx(A))) #giá thị của f(x) khi x bằng A

def cau_1b():
    print("Câu 1b:")
    print("g(0) = " + str(gx(0))) #giá thị của g(x) khi x bằng 0
    print("g(1) = " + str(gx(1))) #giá thị của g(x) khi x bằng 1
    print("g(A) = " + str(gx(A))) #giá thị của g(x) khi x bằng A

def cau_1c():
    fx = lambda x: A * x**2 - 2 * A * x + A
    gx = lambda x: -A * x**2 + A**2 * x + A
    x = np.arange(-100, 300, dtype=np.float)
    plt.plot(x, fx(x), color = 'b', label="fx")
    plt.plot(x, gx(x), color = 'g', label="gx")

    plt.title("Câu 1c")
    plt.legend()
    plt.grid()
    plt.show()

def cau_1d():
    x = np.arange(-10, 10.1, 0.1)
    fx = lambda x: A * x**2 - 2 * A * x + A

    y = list( map( fx, x))
    yStretched = list( map( fx, x / (B + 2)))

    plt.plot(x,y,label="original graph")
    plt.plot(x,yStretched,label="stretched horizontally graph")

    plt.title("câu 1d")
    plt.legend()
    plt.show()

def cau_1e():
    fx = lambda x: A * x**2 - 2 * A * x + A
    gx = lambda x: -A * x**2 + A**2 * x + A
    x = np.arange(-100, 300, dtype=np.float)
    plt.plot(x, fx(x), color = 'b', label="fx")
    plt.plot(x, gx(x), color = 'g', label="gx")

    x = sp.symbols('x')
    fx = A * x**2 - 2 * A * x + A
    gx = -A * x**2 + A**2 * x + A

    x_root = sp.solve(fx - gx)
    
    y_root0 = fx.subs(x, x_root[0])
    y_root1 = fx.subs(x, x_root[1])

    print("Toạ độ X1:(",x_root[0],",",y_root0,")")
    print("Toạ độ X2:(",x_root[1],",",y_root1,")")

    plt.plot(x_root[0], y_root0, 'ro')
    plt.plot(x_root[1], y_root1, 'ro')

    plt.title("Câu 1e")
    plt.grid()
    plt.show()


cau_1a()
print("\n")
cau_1b()
print("\n")
cau_1c()
cau_1d()
print("Câu e")
cau_1e()